### ISSUE TITLE
Confusing output on init if langpack_locales is not set

### ISSUE THREAD

**Issue by xasx** [pnemade/dnf-langpacks#1]
I have not set the `langpack_locales` variable in my `langpacks.conf`.

As a fallback dnf-langpacks then reads from `/var/lib/yum/plugins/langpacks/installed_langpacks` where it finds to defined langpack specification.

However, the log messages I get from DNF are:

```
$ dnf info dnf-langpacks                                 
langpacks: No languages are enabled
Adding de to language list
Adding en to language list
Last metadata expiration check performed 0:57:06 ago on Mon Jul 27 08:20:31 2015.
Installierte Pakete
Name        : dnf-langpacks
Arch        : noarch
Epoch       : 0
Version     : 0.11.1
Release     : 1.fc22
Größe       : 75 k
Paketquelle : @System
...
```

I also noticed in the code that there should be a message summarizing which languages are actually available - refer to [this line](https://github.com/pnemade/dnf-langpacks/blob/f3beca3b104e028e46ef2ecbfb55f7400930c3d2/langpacks.py#L744).

If I now set the `langpack_locales` to an empty value, according to doc only `$LANG` would be considered. However the message would be gone.

In my case I would simply like to have output as follows:

```
Adding de to language list
Adding en to language list
langpacks: enabled languages are: de en
```

I guess that would also hold for several other constellations.

As a side note: I use Fedora, it might have an outdated version -- from what I see, I interpret that recent versions do not output any message at all when initializing, do they?

**Comment by pnemade** [comment]
Fixed with 0.14.0 release. Please check. Closing now. If any issues still found, reply here.
